NPM module
ShpilevskyAndrei/Modal-Popup-in-Angular pull request #1
Opened 2022-05-31 09:45 UTC by ShpilevskyAndrei

to do:
add config for adding event on click on button of toast
add slide out when toast is in closing
add correct width for 'long' and 'short' config

bugs:
too long text of title and message is over the board of toast
position of toasts in layout is not a center (It's on left)

2022-05-31 10:15 UTC, aleskurch requested changes

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast-data-service.ts
> +        const id = Math.random();
Empty row after  `const id = Math.random();`

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast/toast.component.html
> +{{ toastData?.width }}"
Please use `[ngClass]` or/and `[style]`

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast/toast.component.html
> +    id="toast"
I guess U dont need it

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast/toast.component.html
> +                    {{ toastData?.message || "You didn't entry some message" }}
`|| "You didn't entry some message" ` will be not needed if U will use patter I described above

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast/toast.component.html
> +            <mat-icon class="button-pointer" (click)="closeToast()"
`class="button-pointer"` use some more descriptive name

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast/toast.component.html
> +            {{ toastData?.buttonText || actionButtonTextGenerator() }}
Same as with message

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast/toast.component.scss
> +@media only screen and (max-width: 600px) {
Shift @media and @keyframes to bottom

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast/toast.component.scss
> +.toast {
Wrap with :host{}

Check it everywhere

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast/toast.component.scss
> +    animation-name: slideIn;
Check ability to combine 9 & 10 under general attribute `animation: `

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast/toast.component.scss
> +    height: auto;
R U sure about this attribute?

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast/toast.component.ts
> +    public icon(): IconType | null {
it's look like like getter. Read about them and add here

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast/toast.component.ts
> +    public actionButtonTextGenerator(): ButtonType | null {
Same

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toast/toast.component.ts
> +        console.log('pressed button');
Delete

2022-05-31 10:15 UTC, aleskurch commented on src/app/toasts/toasts-layout/toasts-layout.component.ts
> +    public toasts$: Observable<IToastOptions[] | null> =
Check is null alteration in type is really needed

2022-05-31 10:18 UTC, aleskurch commented
<img width="495" alt="Screenshot 2022-05-31 at 13 16 56" src="https://user-images.githubusercontent.com/47333445/171151477-0912bb90-bbb8-4432-a47a-634252750a62.png">
Cross look like too big. I guess 20px will be enough

2022-05-31 13:53 UTC, ShpilevskyAndrei commented on src/app/form/form.component.html
> +    <mat-button-toggle (click)="returnToastOptions()"
done

2022-06-01 08:11 UTC, ShpilevskyAndrei commented on src/app/toasts/toast/toast.component.html
> +                <mat-icon class="icon {{ toastData?.toastType }}-icon">{{
done

2022-06-01 08:11 UTC, ShpilevskyAndrei commented on src/app/toasts/toast/toast.component.html
> +                    {{ toastData?.title || "You didn't entry some title" }}
done

2022-06-01 08:11 UTC, ShpilevskyAndrei commented on src/app/toasts/toast/toast.component.scss
> +    animation-name: slideIn;
combined

2022-06-01 08:20 UTC, ShpilevskyAndrei commented on src/app/toasts/toast-sevice.ts
> +export class ToastService {
done

2022-06-01 08:22 UTC, ShpilevskyAndrei commented on src/app/toasts/toast/toast.component.ts
> +export class ToastComponent {
done

2022-06-01 08:23 UTC, ShpilevskyAndrei commented on src/app/toasts/toast/toast.component.ts
> +    selector: 'app-toast',
app-agroex-toast

2022-06-01 08:26 UTC, ShpilevskyAndrei commented on src/app/toasts/toasts-layout/toasts-layout.component.ts
> +export class ToastsLayoutComponent {
renamed

2022-06-01 09:14 UTC, aleskurch requested changes

2022-06-01 09:14 UTC, aleskurch commented on src/app/agroex-toasts/agroex-toast-data.service.ts
> +    public deleteToast(id: number | undefined): void {
U will have not undifined id

2022-06-01 09:14 UTC, aleskurch commented on src/app/agroex-toasts/agroex-toast/agroex-toast.component.html
> +                <mat-icon class="icon {{ toastData.toastType }}-icon">{{
I guess I wrote comment about it

2022-06-01 09:14 UTC, aleskurch commented on src/app/agroex-toasts/agroex-toast/agroex-toast.component.html
> +            *ngIf="toastData?.buttonText"
place it 2 rows upper

2022-06-01 09:14 UTC, aleskurch commented on src/app/agroex-toasts/agroex-toast/agroex-toast.component.ts
> +    changeDetection: ChangeDetectionStrategy.OnPush, //in all
Delete commnet

2022-06-01 09:14 UTC, aleskurch commented on src/app/agroex-toasts/agroex-toast/agroex-toast.component.ts
> +    @ViewChild('toast') public toast: ElementRef | null = null;
With correct es lint you will dont need assignment and => `| null`

2022-06-01 09:14 UTC, aleskurch commented on src/app/agroex-toasts/agroex-toast/agroex-toast.component.ts
> +    }
Actually could we make 2 constant with keys as ToastType keys and values ActionButtonType instead of switch. And same for previous getter

2022-06-01 09:14 UTC, aleskurch commented on src/app/agroex-toasts/agroex-toast/agroex-toast.component.ts
> +    @ViewChild('toast') public toast: ElementRef | null = null;
Also  ElementRef is generic so use ElementRef<HTMLDivElement>

2022-06-01 09:14 UTC, aleskurch commented on src/app/agroex-toasts/agroex-toast/agroex-toast.component.ts
> +            (this.toast.nativeElement as HTMLDivElement).className +=
If u will use generic u will not need as here

2022-06-01 09:14 UTC, aleskurch commented on src/app/agroex-toasts/agroex-toast/agroex-toast.component.ts
> +        if (changes?.['toastData']?.firstChange) {
changes?.toastData?.firstChange

2022-06-01 09:14 UTC, aleskurch commented on src/app/agroex-toasts/agroex-toasts-layout/agroex-toasts-layout.component.ts
> +    templateUrl: './agroex-toasts-layout.component.html',
Change detection strategy here

2022-06-01 09:14 UTC, aleskurch commented on src/app/app.component.ts
> +    styleUrls: ['./app.component.scss'],
Change detection strategy

2022-06-01 09:14 UTC, aleskurch commented on src/app/form/form.component.ts
> +    styleUrls: ['./form.component.scss'],
Change detection strategy

2022-06-01 09:14 UTC, aleskurch commented on src/app/agroex-toasts/agroex-toast-data.service.ts
> +@Injectable()
ProvideIn: 'root'

2022-06-01 09:14 UTC, aleskurch commented on src/app/agroex-toasts/agroex-toast.service.ts
> +@Injectable()
ProvideIn: 'root'

2022-06-01 09:15 UTC, ShpilevskyAndrei commented on src/app/agroex-toasts/agroex-toast-data.service.ts
> +    public deleteToast(id: number | undefined): void {
agree)

2022-06-01 09:24 UTC, ShpilevskyAndrei commented on src/app/agroex-toasts/agroex-toast-data.service.ts
> +    public deleteToast(id: number | undefined): void {
but

2022-06-01 09:29 UTC, ShpilevskyAndrei commented on src/app/agroex-toasts/agroex-toast-data.service.ts
> +    public deleteToast(id: number | undefined): void {
in Argument of type 'number | undefined' is not assignable to parameter of type 'number'.   Type 'undefined' is not assignable to type 'number'.

2022-06-01 09:47 UTC, ShpilevskyAndrei commented on src/app/agroex-toasts/agroex-toast-data.service.ts
> +    public deleteToast(id: number | undefined): void {
done

2022-06-01 10:39 UTC, ShpilevskyAndrei commented on src/app/agroex-toasts/agroex-toasts-layout/agroex-toasts-layout.component.ts
> +    templateUrl: './agroex-toasts-layout.component.html',
done

2022-06-01 10:47 UTC, ShpilevskyAndrei commented on src/app/form/form.component.ts
> +    styleUrls: ['./form.component.scss'],
done

2022-06-01 10:58 UTC, ShpilevskyAndrei commented on src/app/agroex-toasts/agroex-toast.service.ts
> +@Injectable()
added

2022-06-01 13:14 UTC, ShpilevskyAndrei commented on src/app/agroex-toasts/agroex-toast/agroex-toast.component.ts
> +    }
done

2022-06-01 20:52 UTC, AliaksandraPozniak commented on projects/ngx-agroex-toast/src/lib/agroex-toast/agroex-toast.component.html
> +                    {{ toastData?.message }}
You can remove '?' here since you are checking toastData?.message in ngIf

2022-06-01 21:07 UTC, AliaksandraPozniak commented on src/app/form/form.component.html
> +                        [(ngModel)]="toastOption.toastType"
I would propose to use Reactive Form instead of Template Driven Form. Could you change ngModel to  formControlName and create a formGroup?

2022-06-01 21:07 UTC, AliaksandraPozniak commented on src/app/form/form.component.html
> +                        [(ngModel)]="toastOption.toastType"
https://blog.angular-university.io/introduction-to-angular-2-forms-template-driven-vs-model-driven/

2022-06-06 08:45 UTC, aleskurch approved these changes

2022-06-06 11:23 UTC, merged